# Generated by Django 6.0.4 on 2026-09-17 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('st_name', models.CharField(max_length=30)),
                ('program', models.CharField(max_length=15)),
                ('st_cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('st_city', models.CharField(max_length=20)),
            ],
        ),
    ]
